export const quranSurahs = [
  {
    id: 1,
    url: "al-fatihah",
    engNam: "Al-Fatihah",
    arName: "الفاتحة",
    nameMeaning: "The Opening",
    numberOfAyat: 7,
  },
  {
    id: 2,
    url: "al-baqarah",
    engNam: "Al-Baqarah",
    arName: "البقرة",
    nameMeaning: "The Cow",
    numberOfAyat: 286,
  },
  {
    id: 3,
    url: "ali-imran",
    engNam: "Ali 'Imran",
    arName: "آل عمران",
    nameMeaning: "The Family of Imran",
    numberOfAyat: 200,
  },
  {
    id: 4,
    url: "an-nisa",
    engNam: "An-Nisa'",
    arName: "النساء",
    nameMeaning: "The Women",
    numberOfAyat: 176,
  },
  {
    id: 5,
    url: "al-maidah",
    engNam: "Al-Ma'idah",
    arName: "المائدة",
    nameMeaning: "The Table Spread",
    numberOfAyat: 120,
  },
  {
    id: 6,
    url: "al-anam",
    engNam: "Al-An'am",
    arName: "الأنعام",
    nameMeaning: "The Cattle",
    numberOfAyat: 165,
  },
  {
    id: 7,
    url: "al-araf",
    engNam: "Al-A'raf",
    arName: "الأعراف",
    nameMeaning: "The Heights",
    numberOfAyat: 206,
  },
  {
    id: 8,
    url: "al-anfal",
    engNam: "Al-Anfal",
    arName: "الأنفال",
    nameMeaning: "The Spoils of War",
    numberOfAyat: 75,
  },
  {
    id: 9,
    url: "at-tawbah",
    engNam: "At-Tawbah",
    arName: "التوبة",
    nameMeaning: "The Repentance",
    numberOfAyat: 129,
  },
  {
    id: 10,
    url: "yunus",
    engNam: "Yunus",
    arName: "يونس",
    nameMeaning: "Jonah",
    numberOfAyat: 109,
  },
  {
    id: 11,
    url: "hud",
    engNam: "Hud",
    arName: "هود",
    nameMeaning: "Hud",
    numberOfAyat: 123,
  },
  {
    id: 12,
    url: "yusuf",
    engNam: "Yusuf",
    arName: "يوسف",
    nameMeaning: "Joseph",
    numberOfAyat: 111,
  },
  {
    id: 13,
    url: "ar-rad",
    engNam: "Ar-Ra'd",
    arName: "الرعد",
    nameMeaning: "The Thunder",
    numberOfAyat: 43,
  },
  {
    id: 14,
    url: "ibrahin",
    engNam: "Ibrahim",
    arName: "إبراهيم",
    nameMeaning: "Abraham",
    numberOfAyat: 52,
  },
  {
    id: 15,
    url: "al-hijr",
    engNam: "Al-Hijr",
    arName: "الحجر",
    nameMeaning: "The Rocky Tract",
    numberOfAyat: 99,
  },
  {
    id: 16,
    nameMeaning: "The Bee",
    url: "an-nahl",
    engNam: "An-Nahl",
    numberOfAyat: 128,
    arName: "النحل",
  },
  {
    id: 17,
    nameMeaning: "The Night Journey",
    url: "al-isra",
    engNam: "Al-Isra",
    numberofAyat: 111,
    arName: "الإسراء",
  },
  {
    id: 18,
    nameMeaning: "The Cave",
    url: "al-kahf",
    engNam: "Al-Kahf",
    numberOfAyat: 110,
    arName: "الكهف",
  },
  {
    id: 19,
    nameMeaning: "Mary",
    url: "maryam",
    engNam: "Maryam",
    numberOfAyat: 98,
    arName: "مريم",
  },
  {
    id: 20,
    nameMeaning: "Ta Ha",
    url: "taha",
    engNam: "Ta Ha",
    numberOfAyat: 135,
    arName: "طه",
  },
  {
    id: 21,
    nameMeaning: "The Prophets",
    url: "al-anbiya",
    engNam: "Al-Anbiya",
    numberOfAyat: 112,
    arName: "الأنبياء",
  },
  {
    id: 22,
    nameMeaning: "The Pilgrimage",
    url: "al-hajj",
    engNam: "Al-Hajj",
    numberOfAyat: 78,
    arName: "الحج",
  },
  {
    id: 23,
    nameMeaning: "The Believers",
    url: "Al-muminoon",
    engNam: "Al-Muminoon",
    numberOfAyat: 118,
    arName: "المؤمنون",
  },
  {
    id: 24,
    nameMeaning: "The Light",
    url: "an-noor",
    engNam: "An-Noor",
    numberOfAyat: 64,
    arName: "النور",
  },
  {
    id: 25,
    nameMeaning: "The Criterion",
    url: "al-furqan",
    engNam: "Al-Furqan",
    numberOfAyat: 77,
    arName: "الفرقان",
  },
  {
    id: 26,
    nameMeaning: "The Poets",
    url: "ash-shuara",
    engNam: "Ash-Shuara",
    numberOfAyat: 227,
    arName: "الشعراء",
  },
  {
    id: 27,
    nameMeaning: "The Ant",
    url: "an-naml",
    engNam: "An-Naml",
    numberOfAyat: 93,
    arName: "النمل",
  },
  {
    id: 28,
    nameMeaning: "The Stories",
    url: "al-qasas",
    engNam: "Al-Qasas",
    numberOfAyat: 88,
    arName: "القصص",
  },
  {
    id: 29,
    nameMeaning: "The Spider",
    url: "al-ankaboot",
    engNam: "Al-Ankaboot",
    numberOfAyat: 69,
    arName: "العنكبوت",
  },

  {
    id: 30,
    nameMeaning: "The Romans",
    url: "ar-room",
    engNam: "Ar-Room",
    numberOfAyat: 60,
    arName: "الروم",
  },
  {
    id: 31,
    nameMeaning: "Luqman",
    url: "luqman",
    engNam: "Luqman",
    numberOfAyat: 34,
    arName: "لقمان",
  },
  {
    id: 32,
    nameMeaning: "The Prostration",
    url: "as-sajdah",
    engNam: "As-Sajdah",
    numberOfAyat: 30,
    arName: "السجدة",
  },
  {
    id: 33,
    nameMeaning: "The Confederates",
    url: "al-ahzab",
    engNam: "Al-Ahzab",
    numberOfAyat: 73,
    arName: "الأحزاب",
  },
  {
    id: 34,
    nameMeaning: "Sheba",
    url: "seba",
    engNam: "Saba",
    numberOfAyat: 54,
    arName: "سبأ",
  },
  {
    id: 35,
    nameMeaning: "The Originator",
    url: "fatir",
    engNam: "Fatir",
    numberOfAyat: 45,
    arName: "فاطر",
  },
  {
    id: 36,
    nameMeaning: "Ya Sin",
    url: "ya-sin",
    engNam: "Ya Sin",
    numberOfAyat: 83,
    arName: "يس",
  },
  {
    id: 37,
    nameMeaning: "The Ranks",
    url: "as-saaffat",
    engNam: "As-Saaffat",
    numberOfAyat: 182,
    arName: "الصافات",
  },
  {
    id: 38,
    nameMeaning: "Sad",
    url: "sad",
    engNam: "Sad",
    numberOfAyat: 88,
    arName: "ص",
  },
  {
    id: 39,
    nameMeaning: "The Groups",
    url: "az-zumar",
    engNam: "Az-Zumar",
    numberOfAyat: 75,
    arName: "الزمر",
  },
  {
    id: 40,
    nameMeaning: "The Forgiver",
    url: "ghafir",
    engNam: "Ghafir",
    numberOfAyat: 85,
    arName: "غافر",
  },
  {
    id: 41,
    nameMeaning: "Explained in Detail",
    url: "fussilat",
    engNam: "Fussilat",
    numberOfAyat: 54,
    arName: "فصلت",
  },
  {
    id: 42,
    nameMeaning: "The Consultation",
    url: "ash-shuraa",
    engNam: "Ash-Shuraa",
    numberOfAyat: 53,
    arName: "الشورى",
  },
  {
    id: 43,
    nameMeaning: "Ornaments of Gold",
    url: "az-zukhruf",
    engNam: "Az-Zukhruf",
    numberOfAyat: 89,
    arName: "الزخرف",
  },
  {
    id: 44,
    nameMeaning: "Smoke",
    url: "ad-dukhan",
    engNam: "Ad-Dukhan",
    numberOfAyat: 59,
    arName: "الدخان",
  },
  {
    id: 45,
    url: "al-jathiyah",
    engNam: "Al-Jathiyah",
    nameMeaning: "The Crouching",
    numberOfAyat: 37,
    arName: "الجاثية",
  },
  {
    id: 46,
    url: "al-ahqaf",
    engNam: "Al-Ahqaf",
    nameMeaning: "The Wind-Curved Sandhills",
    numberOfAyat: 35,
    arName: "الأحقاف",
  },
  {
    id: 47,
    url: "muhammad",
    engNam: "Muhammad",
    nameMeaning: "Muhammad",
    numberOfAyat: 38,
    arName: "محمد",
  },
  {
    id: 48,
    url: "al-fath",
    engNam: "Al-Fath",
    nameMeaning: "The Victory",
    numberOfAyat: 29,
    arName: "الفتح",
  },
  {
    id: 49,
    url: "al-hujurat",
    engNam: "Al-Hujurat",
    nameMeaning: "The Inner Apartments",
    numberOfAyat: 18,
    arName: "الحجرات",
  },
  {
    id: 50,
    url: "qaf",
    engNam: "Qaf",
    nameMeaning: "The Letter Qaf",
    numberOfAyat: 45,
    arName: "ق",
  },
  {
    id: 51,
    url: "adh-dhariyat",
    engNam: "Adh-Dhariyat",
    nameMeaning: "The Winnowing Winds",
    numberOfAyat: 60,
    arName: "الذاريات",
  },
  {
    id: 52,
    url: "at-tur",
    engNam: "At-Tur",
    nameMeaning: "The Mount",
    numberOfAyat: 49,
    arName: "الطور",
  },
  {
    id: 53,
    url: "an-najm",
    engNam: "An-Najm",
    nameMeaning: "The Star",
    numberOfAyat: 62,
    arName: "النجم",
  },
  {
    id: 54,
    url: "al-qamar",
    engNam: "Al-Qamar",
    nameMeaning: "The Moon",
    numberOfAyat: 55,
    arName: "القمر",
  },
  {
    id: 55,
    url: "ar-rahman",
    engNam: "Ar-Rahman",
    nameMeaning: "The Beneficent",
    numberOfAyat: 78,
    arName: "الرحمن",
  },
  {
    id: 56,
    url: "al-waqiah",
    engNam: "Al-Waqi'ah",
    nameMeaning: "The Inevitable",
    numberOfAyat: 96,
    arName: "الواقعة",
  },
  {
    id: 57,
    nameMeaning: "The Iron",
    url: "al-hadid",
    engNam: "al-Hadid",
    arName: "الحديد",
    numberOfAyat: 29,
  },
  {
    id: 58,
    nameMeaning: "The Debate",
    url: "al-mujadila",
    engNam: "al-Mujadila",
    arName: "المجادلة",
    numberOfAyat: 22,
  },
  {
    id: 59,
    nameMeaning: "The Gathering",
    url: "al-hashr",
    engNam: "al-Hashr",
    arName: "الحشر",
    numberOfAyat: 24,
  },
  {
    id: 60,
    nameMeaning: "The Examined One",
    url: "al-mumtahanah",
    engNam: "al-Mumtahanah",
    arName: "الممتحنة",
    numberOfAyat: 13,
  },
  {
    id: 61,
    nameMeaning: "The Ranks",
    url: "as-saff",
    engNam: "as-Saff",
    arName: "الصفّ",
    numberOfAyat: 14,
  },
  {
    id: 62,
    nameMeaning: "Friday",
    url: "al-jumuah",
    engNam: "al-Jumu'ah",
    arName: "الجمعة",
    numberOfAyat: 11,
  },
  {
    id: 63,
    nameMeaning: "The Hypocrites",
    url: "al-munafiqoon",
    engNam: "al-Munafiqoon",
    arName: "المنافقون",
    numberOfAyat: 11,
  },
  {
    id: 64,
    nameMeaning: "The Loss and Gain",
    url: "at-taghabun",
    engNam: "at-Taghabun",
    arName: "التغابن",
    numberOfAyat: 18,
  },
  {
    id: 65,
    nameMeaning: "The Divorce",
    url: "at-talaq",
    engNam: "at-Talaq",
    arName: "الطلاق",
    numberOfAyat: 12,
  },
  {
    id: 66,
    nameMeaning: "The Prohibition",
    url: "at-tahrim",
    engNam: "at-Tahrim",
    arName: "التحريم",
    numberOfAyat: 12,
  },
  {
    id: 67,
    nameMeaning: "The Kingdom",
    url: "al-mulk",
    engNam: "al-Mulk",
    arName: "الملك",
    numberOfAyat: 30,
  },
  {
    id: 68,
    nameMeaning: "The Pen",
    url: "al-qalam",
    engNam: "al-Qalam",
    arName: "القلم",
    numberOfAyat: 52,
  },
  {
    id: 69,
    nameMeaning: "The Sure Reality",
    url: "al-haaqqa",
    engNam: "al-Haaqqa",
    arName: "الحاقة",
    numberOfAyat: 52,
  },
  {
    id: 70,
    nameMeaning: "Ways of Ascent",
    url: "al-maaarij",
    engNam: "al-Ma'aarij",
    arName: "المعارج",
    numberOfAyat: 44,
  },
  {
    id: 71,
    nameMeaning: "Noah",
    url: "nooh",
    engNam: "Nooh",
    arName: "نوح",
    numberOfAyat: 28,
  },
  {
    id: 72,
    nameMeaning: "The Jinn",
    url: "al-jinn",
    engNam: "al-Jinn",
    arName: "الجن",
    numberOfAyat: 28,
  },
  {
    id: 73,
    nameMeaning: "The Enwrapped",
    url: "al-muzzammil",
    engNam: "al-Muzzammil",
    arName: "المزّمِّل",
    numberOfAyat: 20,
  },
  {
    id: 74,
    nameMeaning: "The Cloaked One",
    url: "al-muddaththir",
    engNam: "al-Muddaththir",
    arName: "المدّثر",
    numberOfAyat: 56,
  },
  {
    id: 75,
    nameMeaning: "The Resurrection",
    url: "al-qiyamah",
    engNam: "al-Qiyamah",
    arName: "القيامة",
    numberOfAyat: 40,
  },
  {
    id: 76,
    nameMeaning: "The Human",
    url: "al-insaan",
    engNam: "al-Insaan",
    arName: "الإنسان",
    numberOfAyat: 31,
  },
  {
    id: 77,
    nameMeaning: "Those Sent Forth",
    url: "al-mursalaat",
    engNam: "al-Mursalaat",
    arName: "المرسلات",
    numberOfAyat: 50,
  },
  {
    id: 78,
    arName: "النبأ",
    url: "an-naba",
    engNam: "An-Naba",
    nameMeaning: "The Tidings",
    numberOfAyat: 40,
  },
  {
    id: 79,
    arName: "النازعات",
    url: "an-naziat",
    engNam: "An-Nazi'at",
    nameMeaning: "Those Who Drag Forth",
    numberOfAyat: 46,
  },
  {
    id: 80,
    arName: "عبس",
    url: "abasa",
    engNam: "Abasa",
    nameMeaning: "He Frowned",
    numberOfAyat: 42,
  },
  {
    id: 81,
    arName: "التكوير",
    url: "at-takwir",
    engNam: "At-Takwir",
    nameMeaning: "The Overthrowing",
    numberOfAyat: 29,
  },
  {
    id: 82,
    arName: "الإنفطار",
    url: "al-infitar",
    engNam: "Al-Infitar",
    nameMeaning: "The Cleaving",
    numberOfAyat: 19,
  },
  {
    id: 83,
    arName: "المطففين",
    url: "al-mutaffifin",
    engNam: "Al-Mutaffifin",
    nameMeaning: "Those Who Deal in Fraud",
    numberOfAyat: 36,
  },
  {
    id: 84,
    arName: "الإنشقاق",
    url: "al-inshiqaq",
    engNam: "Al-Inshiqaq",
    nameMeaning: "The Splitting Asunder",
    numberOfAyat: 25,
  },
  {
    id: 85,
    arName: "البروج",
    url: "al-buruj",
    engNam: "Al-Buruj",
    nameMeaning: "The Constellations",
    numberOfAyat: 22,
  },
  {
    id: 86,
    arName: "الطارق",
    url: "at-tariq",
    engNam: "At-Tariq",
    nameMeaning: "The Morning Star",
    numberOfAyat: 17,
  },
  {
    id: 87,
    arName: "الأعلى",
    url: "al-ala",
    engNam: "Al-A'la",
    nameMeaning: "The Most High",
    numberOfAyat: 19,
  },
  {
    id: 88,
    arName: "الغاشية",
    url: "al-ghashiyah",
    engNam: "Al-Ghashiyah",
    nameMeaning: "The Overwhelming",
    numberOfAyat: 26,
  },
  {
    id: 89,
    arName: "الفجر",
    url: "al-fajr",
    engNam: "Al-Fajr",
    nameMeaning: "The Dawn",
    numberOfAyat: 30,
  },
  {
    id: 90,
    arName: "البلد",
    url: "al-balad",
    engNam: "Al-Balad",
    nameMeaning: "The City",
    numberOfAyat: 20,
  },
  {
    id: 91,
    arName: "الشمس",
    url: "ash-shams",
    engNam: "Ash-Shams",
    nameMeaning: "The Sun",
    numberOfAyat: 15,
  },
  {
    id: 92,
    arName: "الليل",
    url: "al-lail",
    engNam: "Al-Lail",
    nameMeaning: "The Night",
    numberOfAyat: 21,
  },
  {
    id: 93,
    arName: "الضحى",
    url: "ad-dhuha",
    engNam: "Ad-Dhuha",
    nameMeaning: "The Morning Hours",
    numberOfAyat: 11,
  },
  {
    id: 94,
    arName: "الشرح",
    url: "ash-sharh",
    engNam: "Ash-Sharh",
    nameMeaning: "The Relief",
    numberOfAyat: 8,
  },
  {
    id: 95,
    arName: "التين",
    url: "at-tin",
    engNam: "At-Tin",
    nameMeaning: "The Fig",
    numberOfAyat: 8,
  },
  {
    id: 96,
    arName: "العلق",
    url: "al-alaq",
    engNam: "Al-Alaq",
    nameMeaning: "The Clot",
    numberOfAyat: 19,
  },
  {
    id: 97,
    arName: "القدر",
    url: "al-qadr",
    engNam: "Al-Qadr",
    nameMeaning: "The Power, Fate",
    numberOfAyat: 5,
  },
  {
    id: 98,
    arName: "البينة",
    url: "al-bayyinah",
    engNam: "Al-Bayyinah",
    nameMeaning: "The Clear Proof",
    numberOfAyat: 8,
  },
  {
    id: 99,
    arName: "الزلزلة",
    url: "az-zalzalah",
    engNam: "Az-Zalzalah",
    nameMeaning: "The Earthquake",
    numberOfAyat: 8,
  },
  {
    id: 100,
    arName: "العاديات",
    url: "al-adiyat",
    engNam: "Al-Adiyat",
    nameMeaning: "The Chargers",
    numberOfAyat: 11,
  },
  {
    id: 101,
    arName: "القارعة",
    url: "al-qariah",
    engNam: "Al-Qariah",
    nameMeaning: "The Calamity",
    numberOfAyat: 11,
  },
  {
    id: 102,
    arName: "التكاثر",
    url: "at-takathur",
    engNam: "At-Takathur",
    nameMeaning: "Competition",
    numberOfAyat: 8,
  },
  {
    id: 103,
    arName: "العصر",
    url: "al-asr",
    engNam: "Al-Asr",
    nameMeaning: "The Declining Day, Epoch",
    numberOfAyat: 3,
  },
  {
    id: 104,
    arName: "الهمزة",
    url: "al-hamazah",
    engNam: "Al-Humazah",
    nameMeaning: "The Slanderer",
    numberOfAyat: 9,
  },
  {
    id: 105,
    arName: "الفيل",
    url: "al-fil",
    engNam: "Al-Fil",
    nameMeaning: "The Elephant",
    numberOfAyat: 5,
  },
  {
    id: 106,
    arName: "قريش",
    url: "quraish",
    engNam: "Quraish",
    nameMeaning: "Quraysh",
    numberOfAyat: 4,
  },
  {
    id: 107,
    arName: "الماعون",
    url: "al-maun",
    engNam: "Al-Maun",
    nameMeaning: "Small Kindnesses",
    numberOfAyat: 7,
  },
  {
    id: 108,
    arName: "الكوثر",
    url: "al-kawthar",
    engNam: "Al-Kawthar",
    nameMeaning: "Abundance",
    numberOfAyat: 3,
  },
  {
    id: 109,
    arName: "الكافرون",
    url: "al-kafirun",
    engNam: "Al-Kafirun",
    nameMeaning: "The Disbelievers",
    numberOfAyat: 6,
  },
  {
    id: 110,
    arName: "النصر",
    url: "an-nasr",
    engNam: "An-Nasr",
    nameMeaning: "Divine Support",
    numberOfAyat: 3,
  },
  {
    id: 111,
    arName: "المسد",
    url: "al-nasad",
    engNam: "Al-Masad",
    nameMeaning: "The Palm Fiber",
    numberOfAyat: 5,
  },
  {
    id: 112,
    arName: "الإخلاص",
    url: "al-ikhlas",
    engNam: "Al-Ikhlas",
    nameMeaning: "Sincerity",
    numberOfAyat: 4,
  },
  {
    id: 113,
    arName: "الفلق",
    url: "al-falaq",
    engNam: "Al-Falaq",
    nameMeaning: "The Daybreak",
    numberOfAyat: 5,
  },
  {
    id: 114,
    arName: "الناس",
    url: "an-nas",
    engNam: "An-Nas",
    nameMeaning: "Mankind",
    numberOfAyat: 6,
  },
];
